### ISSUE TITLE
404 {'error': 'no collection found for user'}

### ISSUE THREAD

**Issue by twack** [CoolCoderSJ/HCGateway#10]
Hello Kumar,

I have installed the APK and created the user on the db running on your provided server. It is not on a local server. I have a couple of observations:

1. The downloaded and installed app from the github V1.1.1 release repo says it is version 0.1.0 in the app version on the phone. Is this correct?
2. While the app is syncing on my Android (V12) device, the progress appears to hang near the end. The message on the screen is: HCGateway is currently syncing... [19/19]. I have looked at the Health Connect App history and I can see the HCGateway App is reading from Health Connect every 2 hours (default).
3. On a Raspberry Pi I am running a small python test script which logs in using uname/pwd and attempts to fetch "steps". It retrieves the "sessid" and uses as follows:

```
  import requests
  
  url = "https://api.hcgateway.shuchir.dev/api/login"
  headers = {
      "Content-Type": "application/json"
  }
  payload = {
      "username": "xxxxxx", #fake for this issue doc
      "password": "yyyyyy"
  }
  
  response = requests.post(url, headers=headers, json=payload)
  
  print(response.status_code)
  print(response.json())
  user_id = response.json()['sessid']
  
  method = "steps" 
  url = f"https://api.hcgateway.shuchir.dev/api/fetch/{method}"
  headers = {
      "Content-Type": "application/json"
  }
  payload = {
      "userid": user_id,
      # "queries": ["string"]
  }
  
# Here is where we're getting the error #####################################################
  response = requests.post(url, headers=headers, json=payload)
  
  print(response.status_code)
  print(response.json())
```

I'm seeing error code 404 and {'error': 'no collection found for user'}

Can you please help me with this error?
Tank you advance,
Todd

**Comment by CoolCoderSJ** [comment]
Hello Todd,

1. I seem to have forgotten to change the version value within the app itself. v1.1.1 is the correct identifier.
2. At this moment, the progress bar does not go away after syncing is complete. Looking into how I can fix this.
3. I don't seem to see a sync requested for "steps" under the logs. I would make sure you have allowed HCGateway to read your steps in Health Connect settings. Then, try forcing a sync and try fetching records again. Please let me know if you still run into issues.

Thank you,
Shuchir
