### ISSUE TITLE
Push data to Health Connect

### ISSUE THREAD

**Issue by rlopzc** [CoolCoderSJ/HCGateway#14]
**Is your feature request related to a problem? Please describe**
I want to import my Apple Health data to Android: Google Fit. I have exported all of my Apple health data in a zip file. 

**Describe the solution you'd like**
A REST Endpoint to import the data. I'm thinking of building an apple health importer. 

**Describe alternatives you've considered**
- I've installed Google fit app into my iphone but seems that it only lets Google fit to read one week of data
- There are other apps but they don't support apple health

**Additional context**
I switched from iphone to Android and I want to get my health data.

**Comment by CoolCoderSJ** [comment]
write access has been on my mind for a while - just started work in the `write-access` branch, but no current eta
