### ISSUE TITLE
run in the background

### ISSUE THREAD

**Issue by mocuishlelin** [CoolCoderSJ/HCGateway#15]
First of all, thank you very much for open-sourcing this project. During my use, I noticed that data synchronization stops when the app is not in the foreground. Is this due to my personal device, or does the app not support background operation yet? Do you plan to improve this in future updates?
my device: samsung galaxy s23

**Comment by CoolCoderSJ** [comment]
hey- the app does support background operations. It starts a foreground service compliant with the [new requirements](https://developer.android.com/about/versions/14/changes/fgs-types-required) in order to sync data. However, it's possible your phone may be aggressively killing the service if you aren't on android 14 yet. [dontkillmyapp](https://dontkillmyapp.com/samsung) usually has great tips for making your phone a little kinder to the app!

**Comment by mocuishlelin** [comment]
It might be that I misunderstood the frontend and backend services. The app wasn't killed by the system, and the notification bar shows that synchronization is ongoing. However, if I don't stay on the app interface and instead switch to another app or go back to the home screen, the synchronization stops. When I switch back to the app, the synchronization resumes. Have you encountered the same situation?

**Comment by CoolCoderSJ** [comment]
No, in fact, I'm able to fully close the app and still keep the sync running- https://sharex.shuchir.dev/u/OS8H3G.mp4
strange, I'm not sure why your phone is requiring you to stay on the app screen

**Comment by mocuishlelin** [comment]
> No, in fact, I'm able to fully close the app and still keep the sync running- https://sharex.shuchir.dev/u/OS8H3G.mp4 strange, I'm not sure why your phone is requiring you to stay on the app screen

It should be an issue with my device. I tried several times but got the same result - [video](https://images2.e-gets.com/other/hcgateway.mp4)
I started synchronization at 15/Oct/2024 04:34:05 and switched out of hcgateway. At this point, 1 record was synchronized. Synchronization stopped, and I switched back to hcgateway at 15/Oct/2024 04:38:10, at which point synchronization resumed.
Server log: [log](https://images2.e-gets.com/other/hcgateway.txt)

PS: The video we uploaded contains our user IDs.

**Comment by mocuishlelin** [comment]
> Feel free to delete your video since it exposes your server URL as well (I used a dummy user id) Have you tried disabling battery optimization? Most likely through app info > battery > don't optimize

Yes, I've already set it to be unrestricted in the power management settings, enabled auto-start, and locked the app in the background. No worries, I can just launch it whenever I need to sync. By the way, is there a group or channel available for project discussions?

**Comment by CoolCoderSJ** [comment]
There isn't yet. For now, you can use the discussions tab here!
