### ISSUE TITLE
Failing to use self hosted server with release APK

### ISSUE THREAD

**Issue by fiddur** [CoolCoderSJ/HCGateway#18]
**Describe the bug**
I setup self hosted server with docker.  I can see it logging when just trying out a `url -X POST http://192.168.72.26/api/fetch/something` (just making sure I reach the api).
But when setting the API Base URL to `http://192.168.72.26` there is nothing in the log indicating that a request reaches is.  This is done on the same WIFI, the mobile phone reaches the service with a browser producing a log as well in the api.

I tried creating user account on your server, that worked, so it's not any oddity in the username or password.

**To Reproduce**
1. Run docker setup with port mapping for port 80.'
2. Use the APK from the release, set the api base url to `http://<ip address>`
3. Try creating a user account

**Screenshots**
![Screenshot_20241028-154057](https://github.com/user-attachments/assets/f1a8d752-a87c-4729-b83e-375a0efcbc82)

**Smartphone (please complete the following information):**
 - Device: Motorola Edge 30 Pro
 - OS: Android 13,
 - Build T1SHS33.35-23-20-16

**Additional context**

**Comment by fiddur** [comment]
The error message is just Login Failed

![Screenshot_20241028-155322](https://github.com/user-attachments/assets/d5747228-b0cc-4185-8206-7dd960a18550)

**Comment by CoolCoderSJ** [comment]
Can replicate. This is probably because `android:usesCleartextTraffic` is missing in the manifest. Testing and pushing a fix now.

**Comment by CoolCoderSJ** [comment]
Fixed in v1.3.1. A new APK can be downloaded [here](https://github.com/CoolCoderSJ/HCGateway/releases/download/v1.3.1/app-release.apk)

**Comment by fiddur** [comment]
Now it sits for around 30 seconds and then fails.
Still nothing showing in the logs for the docker from the login attempt.
Other attempts like from the mobile browser to `GET http://192.168.72.26/api/fetch/st` shows up as:

```
192.168.72.248 - - [29/Oct/2024 12:41:22] "GET /api/fetch/st HTTP/1.1" 405 -
```

Will the API backend log a failure to login like this?  I suspect my appwrite backend is not properly configured, but I wanted to see that it at least reaches the backend before debugging that.

**Comment by CoolCoderSJ** [comment]
It should log a failure- at the very least, you'd see `"POST /api/login" 500` or something similar. 
Can you try [this apk](https://github.com/CoolCoderSJ/HCGateway/releases/download/v1.3.1/app-verbose.apk)? It's based on this commit - https://github.com/CoolCoderSJ/HCGateway/commit/999d3f695e134cac97ee48b8def53a3f4bcf642f and shows the full error message when login fails.

**Comment by fiddur** [comment]
It says network error. 

But still, Firefox on same device reaches that domain and gives backend error, while the app doesn't. 

![Screenshot_20241030-120913.png](https://github.com/user-attachments/assets/692f1b2a-994a-458a-8968-14c9053062ec)

**Comment by CoolCoderSJ** [comment]
I just noticed the issue- you have `196.168` as the IP in HCGateway, it should be `192.168`

**Comment by fiddur** [comment]
Oh damn; I thought I double and triple checked the IP :see_no_evil: 

```
192.168.72.248 - - [30/Oct/2024 11:44:46] "POST /api/login HTTP/1.1" 500 -
```

So, now I get more error output in backend.  I guess I need to fix my appwrite stuff.

However, I think appwrite is completely overkill just to get a database.  I'm considering making a fork with a minimal API just for the app ingestion, but storing it in a simpler DB that can be accessed directly from looker studio or other apps, instead of having the API serve its own fetching :thinking: 
For multi-user, it could be a DB wtih clear data ownership.

**Comment by CoolCoderSJ** [comment]
yes, while writing write-access functionality I did realize the app uses barely any of appwrite's functions. A fork would be great! I'm considering migrating to postgres once authentication is complete, simply because it'd involve a lot of rewriting that I want to do after I work on functionality.

In the meantime if you need to get appwrite up, the only configuration you should need is the following:
- Create a project on the dashboard
- Create an API key for the project with the database scope

**Comment by CoolCoderSJ** [comment]
this looks great! Keep in mind I'd prefer not to change the server language, so we won't be able to merge this directly.
