### ISSUE TITLE
Missing data

### ISSUE THREAD

**Issue by Timo2001** [CoolCoderSJ/HCGateway#2]
Great project first of all, wanted some kind of API so I could easily extract exercise data to analyse in python. I am able to extract all exercise data and they do indeed display times at which I performed exercises, but the exact details of the exercises are missing. Take swimming exercise for example (74 is the number for swimming), it does not display the statistics of each lap swum such as the time it took, amount of strokes etc.

I might think this error may be beyond your project as this data can also not be seen in HealthConnect (since your app retrieves data from it, it probably won't be able to display data which is not given by HC).

Example return exerciseSession object:
{
    "$collectionId": "exerciseSession",
    "$createdAt": "2023-11-08T11:06:19.659+00:00",
    "$databaseId": "XXXXX",
    "$id": "255a6937-79df-45c3-906d-3a9562536558",
    "$permissions": [],
    "$updatedAt": "2023-11-14T21:20:29.180+00:00",
    "app": "com.sec.android.app.shealth",
    "data": {
        "exerciseRoute": {},
        "exerciseType": 74,
        "laps": [],
        "notes": null,
        "segments": [],
        "title": null
    }

**Comment by CoolCoderSJ** [comment]
yes, this is a problem I noticed. However, I don't know how Health Connect shows this data though. It's possible the react native to health connect library is missing some data. Unfortunately I am swamped with other work at the moment, I will investigate when I have time. Feel free to take a look if you're interested.
