### ISSUE TITLE
API returns 404 on use

### ISSUE THREAD

**Issue by Studio-Hawaii** [CoolCoderSJ/HCGateway#4]
Hello, for some reason logging in returns 404 and I think I made an account, but im not sure because the app just showed a blank dialog with a dismiss button. Im not sure if it was successful or not because of this, I also noticed just simply typing your api url into a web browser shows "further configuration is required"
<img width="649" alt="Screenshot 2024-03-04 at 11 01 47 PM" src="https://github.com/CoolCoderSJ/HCGateway/assets/96494634/56258b69-09a8-45aa-96d7-30dcbe3f0eec">
Here is what I got while testing with curl:
<img width="529" alt="Screenshot 2024-03-04 at 11 02 58 PM" src="https://github.com/CoolCoderSJ/HCGateway/assets/96494634/1cccd6c4-fbe5-4ce2-bd89-9bb5ca99d325">

Is there any solution or is this a bug?

**Comment by CoolCoderSJ** [comment]
Seems like an issue with how NGINX was set up with my hosted API. It should be fixed now, try giving it another go.
