### ISSUE TITLE
Feature Request: Set api server url on login page

### ISSUE THREAD

**Issue by VikashKothary** [CoolCoderSJ/HCGateway#6]
Thank you for this project. I've been trying to find a easy way to get access to my health connect data and your project seems like the only viable option until Google implements a API of their own. 

An idea that might help beginners, it would be useful if the default apk had a field on the login page to specify the url to the API server.

It would allow users to avoid rebuilding the apk to use self hosted servers.

**Comment by CoolCoderSJ** [comment]
Sounds like a great idea! I will attempt to add this over the next few weeks, just might be a little delayed.

**Comment by CoolCoderSJ** [comment]
done in https://github.com/CoolCoderSJ/HCGateway/commit/57afeb63eef6d8ac05cfb63451e07295396bedc2
expected v0.1.0 release with this in effect soon.

**Comment by CoolCoderSJ** [comment]
fixed in v1.1.0

**Comment by VikashKothary** [comment]
Thanks so much!
